version: '3.8'

services:
  rag-app:
    build: .
    container_name: rag-app
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      GOOGLE_API_KEY: ${GEMINI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - ./Interface:/app/Interface
      - ./Ingestion:/app/Ingestion
    restart: unless-stopped
    depends_on:
      - chromadb
      - prometheus

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - ./data/processed/vectorstore:/chroma/chroma-data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  grafana-data:

networks:
  default:
    driver: bridge
