global:
  scrape_interval: 95s
  evaluation_interval: 95s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rag-app'
    static_configs:
      - targets: ['rag-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 90s
